/* Moa — UI strings: key → [English, 한국어]. {x} = variable, {n|one|other} = English plural. */
export default {
  "sync.pending": ["Unsaved", "저장 대기"],
  "sync.saving": ["Saving…", "저장 중…"],
  "sync.error": ["Save failed", "저장 실패"],
  "sync.loading": ["Loading…", "불러오는 중…"],
  "sync.throttle": ["Pacing {s}s", "속도 조절 {s}초"],
  "auth.cancelled": ["Sign-in cancelled", "로그인을 취소했어요"],
  "auth.failed": ["Sign-in failed ({e})", "로그인 실패 ({e})"],
  "auth.expired": ["Session expired. Please sign in again.", "로그인이 만료됐어요. 다시 로그인해 주세요"],
  "auth.logoutConfirm": ["Sign out? Cached photos on this device will be cleared.", "로그아웃할까요? 이 기기의 사진 캐시도 지워요."],
  "auth.signedOut": ["Signed out", "로그아웃했어요"],
  "welcome.lead": ["Shared albums with friends,<br>kept in your private GitHub repos.", "친구와 함께 채우는 공유앨범.<br>사진은 내 GitHub 비공개 저장소에."],
  "welcome.invited": ["{by} invited you to {repo}", "{by}님이 {repo} 앨범에 초대했어요"],
  "welcome.signin": ["Continue with GitHub", "GitHub로 시작하기"],
  "welcome.tokenAdvanced": ["Connect with a token", "토큰으로 연결"],
  "welcome.connect": ["Connect a repository", "저장소 연결"],
  "welcome.repo": ["GitHub repository", "GitHub 저장소"],
  "welcome.token": ["Access token", "액세스 토큰"],
  "welcome.advanced": ["Advanced", "고급"],
  "welcome.branch": ["Branch", "브랜치"],
  "welcome.api": ["API URL", "API 주소"],
  "welcome.connectBtn": ["Connect", "연결하기"],
  "common.cancel": ["Cancel", "취소"],
  "welcome.repoFormat": ["Use the form owner/repo", "\"아이디/저장소\" 형식으로 적어주세요"],
  "common.checking": ["Checking…", "확인 중…"],
  "auth.signOut": ["Sign out", "로그아웃"],
  "home.title": ["Albums", "앨범"],
  "home.new": ["New album", "새 앨범 만들기"],
  "common.back": ["Back", "돌아가기"],
  "home.loadFailed": ["Couldn't load albums", "앨범 목록을 못 불러왔어요"],
  "home.noInviteYet": ["No invite for {repo} yet. Share your username {me}.", "{repo} 초대가 아직 없어요. 아이디 {me}를 알려주세요."],
  "home.invites": ["Invitations", "받은 초대"],
  "home.accept": ["Accept", "수락"],
  "home.public": ["Public", "공개"],
  "home.viaToken": ["Token", "토큰"],
  "home.empty": ["No albums yet", "아직 앨범이 없어요"],
  "home.accepting": ["Accepting…", "수락 중…"],
  "home.joined": ["Joined {name}", "{name} 앨범에 참여했어요"],
  "newAlbum.title": ["New album", "새 앨범"],
  "newAlbum.name": ["Name", "앨범 이름"],
  "newAlbum.namePh": ["Summer trip 2026", "2026 제주 여행"],
  "newAlbum.repo": ["Repository name", "저장소 이름"],
  "common.create": ["Create", "만들기"],
  "newAlbum.default": ["Our album", "우리 앨범"],
  "newAlbum.badName": ["Letters, numbers, - _ . only", "영문, 숫자, - _ . 만 쓸 수 있어요"],
  "common.creating": ["Creating…", "만드는 중…"],
  "newAlbum.taken": ["That name is taken", "이미 있는 이름이에요"],
  "rate.wait": ["GitHub rate limit — waiting {s}s", "GitHub 요청 한도 — {s}초 대기"],
  "offline": ["Offline — showing the last copy", "오프라인 — 마지막으로 불러온 앨범"],
  "open.failed": ["Can't open this album", "열 수 없어요"],
  "common.retry": ["Retry", "다시 시도"],
  "open.reenterToken": ["Re-enter token", "토큰 다시 입력"],
  "refresh.new": ["{n} new {n|photo|photos}", "새 사진 {n}장"],
  "readonly": ["This album is read-only", "읽기 전용 앨범이에요"],
  "save.failed": ["Couldn't save: {e}. Retrying soon.", "저장 실패: {e}. 곧 다시 시도해요."],
  "init.notAlbum": ["Not a Moa album yet", "아직 Moa 앨범이 아니에요"],
  "init.title": ["Start an album here?", "이 저장소에 앨범을 만들까요?"],
  "init.create": ["Create album", "앨범 만들기"],
  "init.done": ["Album created", "앨범을 만들었어요"],
  "cap.over": ["Over the 10 GB guideline", "권장 용량 초과"],
  "cap.used": ["{p} used", "{p} 사용"],
  "cap.left": ["{b} left of 10 GB", "남은 {b} / 10GB"],
  "cap.details": ["Details", "자세히"],
  "lim.repo": ["Repository size · 10 GB", "저장소 크기 · 10GB"],
  "lim.file": ["Single file · 100 MB max", "파일 1개 · 최대 100MB"],
  "lim.fileRec": ["Files over 1 MB", "1MB 넘는 파일"],
  "lim.nPhotos": ["{n}", "{n}장"],
  "lim.dir": ["Files per folder · 3,000", "폴더당 파일 · 3,000개"],
  "lim.index": ["Index file · 1 MB", "앨범 정보 파일 · 1MB"],
  "lim.push": ["Saves · 6 per minute", "저장 속도 · 분당 6회"],
  "lim.perMin": ["{n}/min", "{n}회/분"],
  "plan.tooBig": ["{n} over 100 MB — skipped", "100MB 초과 {n}개 — 제외"],
  "plan.heavy": ["{n} over 50 MB — may fail", "50MB 초과 {n}개 — 실패할 수 있음"],
  "plan.saveOrig": ["Originals off saves ~{b}", "원본 끄면 약 {b} 절약"],
  "plan.over": ["Exceeds 10 GB ({p})", "10GB 초과 ({p})"],
  "plan.after": ["{p} of 10 GB after upload", "업로드 후 {p} 사용"],
  "plan.batches": ["Saved in {n} batches", "{n}번에 나눠 저장"],
  "plan.this": ["This upload ~{b}", "이번 업로드 약 {b}"],
  "plan.left": ["{b} left of 10 GB", "남은 용량 {b} / 10GB"],
  "plan.ack": ["Upload anyway", "그래도 올리기"],
  "empty.album": ["This album is empty", "앨범이 비어 있어요"],
  "empty.library": ["Add your first photos", "첫 사진을 올려보세요"],
  "empty.upload": ["Upload photos", "사진 올리기"],
  "empty.noMatch": ["No matching photos", "조건에 맞는 사진이 없어요"],
  "empty.clear": ["Clear filters", "필터 지우기"],
  "date.more": [" +{n}", " 외 {n}곳"],
  "group.noTag": ["No tags", "태그 없음"],
  "group.noPlace": ["No location", "위치 정보 없음"],
  "view.map": ["Map", "지도"],
  "n.photos": ["{n} {n|photo|photos}", "{n}장"],
  "group.less": ["Show less", "접기"],
  "group.all": ["Show all", "모두 보기"],
  "photo": ["Photo", "사진"],
  "hero.photos": ["{n} {n|photo|photos}", "사진 {n}장"],
  "hero.videos": ["{n} {n|video|videos}", "동영상 {n}개"],
  "hero.live": ["{n} Live", "라이브 {n}"],
  "tab.albums": ["Albums", "앨범"],
  "common.edit": ["Edit", "편집"],
  "hero.members": ["{n} members", "멤버 {n}명"],
  "tab.library": ["Library", "보관함"],
  "sort": ["Sort", "정렬"],
  "sort.newest": ["Newest", "최신순"],
  "sort.oldest": ["Oldest", "오래된순"],
  "place.level": ["Level", "단위"],
  "place.country": ["Country", "나라"],
  "place.city": ["City", "도시"],
  "place.district": ["Neighborhood", "동네"],
  "place.recent": ["Recent", "최근 방문순"],
  "place.count": ["Most photos", "사진 많은순"],
  "place.name": ["Name", "이름순"],
  "chip.all": ["All", "전체"],
  "chip.videos": ["Videos", "동영상"],
  "chip.liked": ["Liked", "좋아요"],
  "map.failed": ["Couldn't load the map", "지도를 불러오지 못했어요"],
  "map.none": ["No photos with location", "위치가 있는 사진이 없어요"],
  "smart.live": ["Live Photos", "라이브 포토"],
  "smart.title": ["Collections", "모아보기"],
  "smart.places": ["Places", "장소"],
  "smart.tags": ["Tags", "태그"],
  "albumEdit.title": ["Edit album", "앨범 편집"],
  "albumEdit.delete": ["Delete album", "앨범 삭제"],
  "common.save": ["Save", "저장"],
  "albumEdit.confirm": ["Delete “{name}”? Photos stay in the library.", "“{name}” 앨범을 삭제할까요? 사진은 보관함에 남아요."],
  "pick.title": ["Add to album", "앨범에 추가"],
  "pick.remove": ["Remove from “{name}”", "“{name}”에서 빼기"],
  "pick.added": ["Added {n} to “{name}”", "“{name}”에 {n}장 추가했어요"],
  "tab.settings": ["Settings", "설정"],
  "set.people": ["People", "함께하는 사람"],
  "set.me": ["you", "나"],
  "invite.title": ["Invite a friend", "친구 초대"],
  "set.album": ["This album", "이 앨범"],
  "set.private": ["Private", "비공개"],
  "set.readonly": ["Read-only", "읽기 전용"],
  "set.storage": ["Storage", "저장 공간"],
  "set.left": ["{b} left", "남은 {b}"],
  "set.originals": ["Originals", "원본"],
  "set.liveVideo": ["Live", "라이브"],
  "set.previews": ["Previews", "미리보기"],
  "set.githubSize": ["Size on GitHub", "GitHub 저장소 크기"],
  "set.limits": ["GitHub limits", "GitHub 한도"],
  "set.albums": ["Albums", "앨범 목록"],
  "set.remove": ["Remove", "제거"],
  "set.allAlbums": ["All albums & invitations", "모든 앨범 · 받은 초대"],
  "set.options": ["Options", "옵션"],
  "set.language": ["Language", "언어"],
  "opt.autoplayLive": ["Play Live Photos on open", "라이브 포토 자동 재생"],
  "opt.keepOriginal": ["Keep originals", "원본 저장"],
  "opt.geocode": ["Look up place names", "장소 이름 찾기"],
  "set.clearCache": ["Clear photo cache", "사진 캐시 비우기"],
  "set.account": ["Account", "계정"],
  "invite.username": ["GitHub username", "GitHub 아이디"],
  "invite.send": ["Send invite", "초대 보내기"],
  "invite.link": ["Invite link", "초대 링크"],
  "invite.copy": ["Copy link", "링크 복사"],
  "invite.share": ["Share", "공유하기"],
  "invite.owner": ["Owner", "주인"],
  "invite.canEdit": ["Can edit", "편집 가능"],
  "invite.viewOnly": ["View only", "보기만"],
  "invite.pending": ["Pending", "수락 대기"],
  "invite.noAccess": ["Only the owner can see this list", "주인만 볼 수 있어요"],
  "invite.badUser": ["Check the username", "아이디를 확인해 주세요"],
  "invite.sending": ["Sending…", "보내는 중…"],
  "invite.sent": ["Invite sent to {u}", "{u}님에게 초대를 보냈어요"],
  "invite.already": ["{u} is already a member", "{u}님은 이미 멤버예요"],
  "invite.noUser": ["{u} — no such GitHub user", "{u} — 없는 아이디예요"],
  "invite.ownerOnly": ["Only the owner can invite", "주인만 초대할 수 있어요"],
  "invite.copied": ["Link copied", "링크를 복사했어요"],
  "common.done": ["Done", "완료"],
  "select": ["Select", "선택"],
  "selected": ["{n} selected", "{n}개 선택"],
  "tags.title": ["Add tags", "태그 달기"],
  "tags.new": ["Tags", "태그"],
  "tags.ph": ["beach, family", "바다, 가족"],
  "common.add": ["Add", "추가"],
  "tags.done": ["Tagged {n} {n|photo|photos}", "{n}장에 태그를 달았어요"],
  "delete.confirm": ["Delete {n} {n|photo|photos} for everyone?", "{n}장을 모두에게서 삭제할까요?"],
  "viewer.videoFailed": ["Couldn't load the video", "동영상을 불러오지 못했어요"],
  "viewer.photoFailed": ["Couldn't load the photo", "사진을 불러오지 못했어요"],
  "viewer.liveFailed": ["Couldn't load the Live Photo", "라이브 영상을 불러오지 못했어요"],
  "viewer.hevc": ["This browser can't play this Live Photo", "이 브라우저는 이 라이브 영상을 재생할 수 없어요"],
  "dl.start": ["Downloading…", "받는 중…"],
  "dl.failed": ["Download failed: {e}", "다운로드 실패: {e}"],
  "info.caption": ["Add a caption…", "설명 추가…"],
  "info.tags": ["Tags", "태그"],
  "info.untag": ["Remove tag", "태그 삭제"],
  "info.addTag": ["Add a tag", "태그 추가"],
  "info.date": ["Date", "날짜"],
  "info.place": ["Place", "장소"],
  "info.onMap": ["Show on map", "지도에서 보기"],
  "info.comments": ["Comments", "댓글"],
  "common.delete": ["Delete", "삭제"],
  "info.addComment": ["Add a comment…", "댓글 달기…"],
  "info.details": ["Details", "정보"],
  "info.dlOriginal": ["Download original", "원본 받기"],
  "info.dlJpeg": ["Download JPEG", "JPEG 받기"],
  "info.dlLive": ["Live video", "라이브 영상"],
  "info.setCover": ["Set as cover", "앨범 커버로"],
  "info.coverSet": ["Cover updated", "커버를 바꿨어요"],
  "place.search": ["Search places", "장소 검색"],
  "place.clear": ["Remove location", "위치 지우기"],
  "place.searching": ["Searching…", "찾는 중…"],
  "place.noResults": ["No results", "결과가 없어요"],
  "up.busy": ["Wait for the current upload to finish", "지금 업로드가 끝난 뒤에 올릴 수 있어요"],
  "up.reading": ["Reading photos…", "사진 확인 중…"],
  "up.withLocation": ["{n} with location", "위치 {n}"],
  "up.dups": ["{n} duplicate skipped", "중복 {n}개 제외"],
  "up.errors": ["{n} unsupported", "불가 {n}"],
  "up.large": ["Large", "대용량"],
  "up.title": ["Upload {n}", "{n}개 올리기"],
  "up.uploading": ["Uploading", "업로드 중"],
  "up.libraryOnly": ["Library only", "보관함에만"],
  "up.go": ["Upload", "업로드"],
  "up.st.dup": ["Already added", "이미 있음"],
  "up.st.processing": ["Processing", "처리 중"],
  "up.st.uploading": ["Uploading {i}/{n}", "올리는 중 {i}/{n}"],
  "up.st.queued": ["Queued", "대기"],
  "up.st.saving": ["Saving", "저장 중"],
  "up.st.done": ["Done", "완료"],
  "up.st.fail": ["Failed", "실패"],
  "save.failedNow": ["Couldn't save: {e}", "저장 실패: {e}"],
  "up.partial": ["{n} uploaded · {f} failed", "{n}개 올림 · {f}개 실패"],
  "up.allDone": ["Uploaded {n}", "{n}개 모두 올렸어요"],
  "set.removeConfirm": ["Remove {repo} from this device? The repository stays.", "이 기기에서 {repo}를 제거할까요? 저장소는 그대로예요."],
  "set.cacheCleared": ["Cache cleared", "캐시를 비웠어요"],
  "select.none": ["Select photos first", "사진을 먼저 선택하세요"],
  "app.title": ["Moa — shared albums", "Moa — 공유앨범"],
  "media.unsupported": ["Unsupported", "지원하지 않는 형식"],
  "media.tooBig": ["Over 100 MB", "100MB 초과"],
  "media.heic": ["This browser can't read HEIC — use Safari or convert to JPEG", "이 브라우저는 HEIC를 열 수 없어요 — Safari를 쓰거나 JPEG로 바꿔 주세요"],
  "media.decode": ["Can't open this image", "이미지를 열 수 없어요"],
  "gh.network": ["Can't reach GitHub", "GitHub에 연결할 수 없어요"],
  "gh.401": ["Token invalid or expired", "토큰이 올바르지 않거나 만료됐어요"],
  "gh.403": ["No write access to this repository", "이 저장소에 쓸 권한이 없어요"],
  "gh.404": ["Repository not found", "저장소를 찾을 수 없어요"],
  "gh.other": ["GitHub error {s}", "GitHub 오류 {s}"],
  "gh.conflict": ["Keeps conflicting with other changes. Try again shortly.", "다른 변경과 계속 충돌해요. 잠시 후 다시 시도하세요"],
  "gh.missing": ["Missing file: {p}", "파일이 없어요: {p}"],
  "aria.switchAlbum": ["Switch album", "앨범 바꾸기"],
  "aria.search": ["Search", "검색"],
  "search.ph": ["Search tags, places, captions, people", "태그, 장소, 설명, 사람 검색"],
  "view.date": ["Date", "날짜"],
  "view.place": ["Places", "장소"],
  "view.tag": ["Tags", "태그"],
  "aria.close": ["Close", "닫기"],
  "aria.playLive": ["Play Live Photo", "라이브 포토 재생"],
  "aria.prev": ["Previous", "이전"],
  "aria.next": ["Next", "다음"],
};
