/* Moa — UI strings: key → [English, 한국어]. {x} = variable, {n|one|other} = English plural. */
export default {
  "sync.pending": ["Unsaved", "저장 대기"],
  "sync.saving": ["Saving…", "저장 중…"],
  "sync.error": ["Save failed", "저장 실패"],
  "sync.loading": ["Loading…", "불러오는 중…"],
  "sync.throttle": ["Pacing {s}s", "속도 조절 {s}초"],
  "auth.cancelled": ["Sign-in cancelled", "로그인을 취소했어요"],
  "auth.failed": ["Sign-in failed ({e})", "로그인 실패 ({e})"],
  "auth.expired": ["Session expired. Please sign in again.", "로그인이 만료됐어요. 다시 로그인해 주세요"],
  "auth.logoutConfirm": ["Sign out? Cached photos on this device will be cleared.", "로그아웃할까요? 이 기기의 사진 캐시도 지워요."],
  "auth.signedOut": ["Signed out", "로그아웃했어요"],
  "welcome.lead": ["Shared albums with friends,<br>kept in your private GitHub repos.", "친구와 함께 채우는 공유앨범.<br>사진은 내 GitHub 비공개 저장소에."],
  "welcome.invited": ["{by} invited you to {repo}", "{by}님이 {repo} 앨범에 초대했어요"],
  "welcome.signin": ["Continue with GitHub", "GitHub로 시작하기"],
  "welcome.tokenAdvanced": ["Connect with a token", "토큰으로 연결"],
  "welcome.connect": ["Connect a repository", "저장소 연결"],
  "welcome.repo": ["GitHub repository", "GitHub 저장소"],
  "welcome.token": ["Access token", "액세스 토큰"],
  "welcome.advanced": ["Advanced", "고급"],
  "welcome.branch": ["Branch", "브랜치"],
  "welcome.api": ["API URL", "API 주소"],
  "welcome.connectBtn": ["Connect", "연결하기"],
  "common.cancel": ["Cancel", "취소"],
  "welcome.repoFormat": ["Use the form owner/repo", "\"아이디/저장소\" 형식으로 적어주세요"],
  "common.checking": ["Checking…", "확인 중…"],
  "auth.signOut": ["Sign out", "로그아웃"],
  "home.title": ["Albums", "앨범"],
  "home.new": ["New album", "새 앨범 만들기"],
  "common.back": ["Back", "돌아가기"],
  "home.loadFailed": ["Couldn't load albums", "앨범 목록을 못 불러왔어요"],
  "home.noInviteYet": ["No invite for {repo} yet. Share your username {me}.", "{repo} 초대가 아직 없어요. 아이디 {me}를 알려주세요."],
  "home.invites": ["Invitations", "받은 초대"],
  "home.accept": ["Accept", "수락"],
  "home.public": ["Public", "공개"],
  "home.viaToken": ["Token", "토큰"],
  "home.empty": ["No albums yet", "아직 앨범이 없어요"],
  "home.accepting": ["Accepting…", "수락 중…"],
  "home.joined": ["Joined {name}", "{name} 앨범에 참여했어요"],
  "newAlbum.title": ["New album", "새 앨범"],
  "newAlbum.name": ["Name", "앨범 이름"],
  "newAlbum.namePh": ["Summer trip 2026", "2026 제주 여행"],
  "newAlbum.repo": ["Repository name", "저장소 이름"],
  "common.create": ["Create", "만들기"],
  "newAlbum.default": ["Our album", "우리 앨범"],
  "newAlbum.badName": ["Letters, numbers, - _ . only", "영문, 숫자, - _ . 만 쓸 수 있어요"],
  "common.creating": ["Creating…", "만드는 중…"],
  "newAlbum.taken": ["That name is taken", "이미 있는 이름이에요"],
  "rate.wait": ["GitHub rate limit — waiting {s}s", "GitHub 요청 한도 — {s}초 대기"],
  "offline": ["Offline — showing the last copy", "오프라인 — 마지막으로 불러온 앨범"],
  "open.failed": ["Can't open this album", "열 수 없어요"],
  "common.retry": ["Retry", "다시 시도"],
  "open.reenterToken": ["Re-enter token", "토큰 다시 입력"],
  "refresh.new": ["{n} new {n|photo|photos}", "새 사진 {n}장"],
  "readonly": ["This album is read-only", "읽기 전용 앨범이에요"],
  "save.failed": ["Couldn't save: {e}. Retrying soon.", "저장 실패: {e}. 곧 다시 시도해요."],
  "init.notAlbum": ["Not a Moa album yet", "아직 Moa 앨범이 아니에요"],
  "init.title": ["Start an album here?", "이 저장소에 앨범을 만들까요?"],
  "init.create": ["Create album", "앨범 만들기"],
  "init.done": ["Album created", "앨범을 만들었어요"],
  "cap.over": ["Over the 10 GB guideline", "권장 용량 초과"],
  "cap.used": ["{p} used", "{p} 사용"],
  "cap.left": ["{b} left of 10 GB", "남은 {b} / 10GB"],
  "cap.details": ["Details", "자세히"],
  "lim.repo": ["Repository size · 10 GB", "저장소 크기 · 10GB"],
  "lim.file": ["Single file · 100 MB max", "파일 1개 · 최대 100MB"],
  "lim.fileRec": ["Files over 1 MB", "1MB 넘는 파일"],
  "lim.nPhotos": ["{n}", "{n}장"],
  "lim.dir": ["Files per folder · 3,000", "폴더당 파일 · 3,000개"],
  "lim.index": ["Index file · 1 MB", "앨범 정보 파일 · 1MB"],
  "lim.push": ["Saves · 6 per minute", "저장 속도 · 분당 6회"],
  "lim.perMin": ["{n}/min", "{n}회/분"],
  "plan.tooBig": ["{n} over 100 MB — skipped", "100MB 초과 {n}개 — 제외"],
  "plan.heavy": ["{n} over 50 MB — may fail", "50MB 초과 {n}개 — 실패할 수 있음"],
  "plan.saveOrig": ["Originals off saves ~{b}", "원본 끄면 약 {b} 절약"],
  "plan.over": ["Exceeds 10 GB ({p})", "10GB 초과 ({p})"],
  "plan.after": ["{p} of 10 GB after upload", "업로드 후 {p} 사용"],
  "plan.batches": ["Saved in {n} batches", "{n}번에 나눠 저장"],
  "plan.this": ["This upload ~{b}", "이번 업로드 약 {b}"],
  "plan.left": ["{b} left of 10 GB", "남은 용량 {b} / 10GB"],
  "plan.ack": ["Upload anyway", "그래도 올리기"],
  "empty.album": ["This album is empty", "앨범이 비어 있어요"],
  "empty.library": ["Add your first photos", "첫 사진을 올려보세요"],
  "empty.upload": ["Upload photos", "사진 올리기"],
  "empty.noMatch": ["No matching photos", "조건에 맞는 사진이 없어요"],
  "empty.clear": ["Clear filters", "필터 지우기"],
  "date.more": [" +{n}", " 외 {n}곳"],
  "group.noTag": ["No tags", "태그 없음"],
  "group.noPlace": ["No location", "위치 정보 없음"],
  "view.map": ["Map", "지도"],
  "n.photos": ["{n} {n|photo|photos}", "{n}장"],
  "group.less": ["Show less", "접기"],
  "group.all": ["Show all", "모두 보기"],
  "photo": ["Photo", "사진"],
  "hero.photos": ["{n} {n|photo|photos}", "사진 {n}장"],
  "hero.videos": ["{n} {n|video|videos}", "동영상 {n}개"],
  "hero.live": ["{n} Live", "라이브 {n}"],
  "tab.albums": ["Albums", "앨범"],
  "common.edit": ["Edit", "편집"],
  "hero.members": ["{n} members", "멤버 {n}명"],
  "tab.library": ["Library", "보관함"],
  "sort": ["Sort", "정렬"],
  "sort.newest": ["Newest", "최신순"],
  "sort.oldest": ["Oldest", "오래된순"],
  "place.level": ["Level", "단위"],
  "place.country": ["Country", "나라"],
  "place.city": ["City", "도시"],
  "place.district": ["Neighborhood", "동네"],
  "place.recent": ["Recent", "최근 방문순"],
  "place.count": ["Most photos", "사진 많은순"],
  "place.name": ["Name", "이름순"],
  "chip.all": ["All", "전체"],
  "chip.videos": ["Videos", "동영상"],
  "chip.liked": ["Liked", "좋아요"],
  "map.failed": ["Couldn't load the map", "지도를 불러오지 못했어요"],
  "map.none": ["No photos with location", "위치가 있는 사진이 없어요"],
  "smart.live": ["Live Photos", "라이브 포토"],
  "smart.title": ["Collections", "모아보기"],
  "smart.places": ["Places", "장소"],
  "smart.tags": ["Tags", "태그"],
  "albumEdit.title": ["Edit album", "앨범 편집"],
  "albumEdit.delete": ["Delete album", "앨범 삭제"],
  "common.save": ["Save", "저장"],
  "albumEdit.confirm": ["Delete “{name}”? Photos stay in the library.", "“{name}” 앨범을 삭제할까요? 사진은 보관함에 남아요."],
  "pick.title": ["Add to album", "앨범에 추가"],
  "pick.remove": ["Remove from “{name}”", "“{name}”에서 빼기"],
  "pick.added": ["Added {n} to “{name}”", "“{name}”에 {n}장 추가했어요"],
  "tab.settings": ["Settings", "설정"],
  "set.people": ["People", "함께하는 사람"],
  "set.me": ["you", "나"],
  "invite.title": ["Invite a friend", "친구 초대"],
  "set.album": ["This album", "이 앨범"],
  "set.private": ["Private", "비공개"],
  "set.readonly": ["Read-only", "읽기 전용"],
  "set.storage": ["Storage", "저장 공간"],
  "set.left": ["{b} left", "남은 {b}"],
  "set.originals": ["Originals", "원본"],
  "set.liveVideo": ["Live", "라이브"],
  "set.previews": ["Previews", "미리보기"],
  "set.githubSize": ["Size on GitHub", "GitHub 저장소 크기"],
  "set.limits": ["GitHub limits", "GitHub 한도"],
  "set.albums": ["Albums", "앨범 목록"],
  "set.remove": ["Remove", "제거"],
  "set.allAlbums": ["All albums & invitations", "모든 앨범 · 받은 초대"],
  "set.options": ["Options", "옵션"],
  "set.language": ["Language", "언어"],
  "opt.autoplayLive": ["Play Live Photos on open", "라이브 포토 자동 재생"],
  "opt.keepOriginal": ["Keep originals", "원본 저장"],
  "opt.geocode": ["Look up place names", "장소 이름 찾기"],
  "set.clearCache": ["Clear photo cache", "사진 캐시 비우기"],
  "set.account": ["Account", "계정"],
  "invite.username": ["GitHub username", "GitHub 아이디"],
  "invite.send": ["Send invite", "초대 보내기"],
  "invite.link": ["Invite link", "초대 링크"],
  "invite.copy": ["Copy link", "링크 복사"],
  "invite.share": ["Share", "공유하기"],
  "invite.owner": ["Owner", "주인"],
  "invite.canEdit": ["Can edit", "편집 가능"],
  "invite.viewOnly": ["View only", "보기만"],
  "invite.pending": ["Pending", "수락 대기"],
  "invite.noAccess": ["Only the owner can see this list", "주인만 볼 수 있어요"],
  "invite.badUser": ["Check the username", "아이디를 확인해 주세요"],
  "invite.sending": ["Sending…", "보내는 중…"],
  "invite.sent": ["Invite sent to {u}", "{u}님에게 초대를 보냈어요"],
  "invite.already": ["{u} is already a member", "{u}님은 이미 멤버예요"],
  "invite.noUser": ["{u} — no such GitHub user", "{u} — 없는 아이디예요"],
  "invite.ownerOnly": ["Only the owner can invite", "주인만 초대할 수 있어요"],
  "invite.copied": ["Link copied", "링크를 복사했어요"],
  "common.done": ["Done", "완료"],
  "select": ["Select", "선택"],
  "selected": ["{n} selected", "{n}개 선택"],
  "tags.title": ["Add tags", "태그 달기"],
  "tags.new": ["Tags", "태그"],
  "tags.ph": ["beach, family", "바다, 가족"],
  "common.add": ["Add", "추가"],
  "tags.done": ["Tagged {n} {n|photo|photos}", "{n}장에 태그를 달았어요"],
  "delete.confirm": ["Delete {n} {n|photo|photos} for everyone?", "{n}장을 모두에게서 삭제할까요?"],
  "viewer.videoFailed": ["Couldn't load the video", "동영상을 불러오지 못했어요"],
  "viewer.photoFailed": ["Couldn't load the photo", "사진을 불러오지 못했어요"],
  "viewer.liveFailed": ["Couldn't load the Live Photo", "라이브 영상을 불러오지 못했어요"],
  "viewer.hevc": ["This browser can't play this Live Photo", "이 브라우저는 이 라이브 영상을 재생할 수 없어요"],
  "dl.start": ["Downloading…", "받는 중…"],
  "dl.failed": ["Download failed: {e}", "다운로드 실패: {e}"],
  "info.caption": ["Add a caption…", "설명 추가…"],
  "info.tags": ["Tags", "태그"],
  "info.untag": ["Remove tag", "태그 삭제"],
  "info.addTag": ["Add a tag", "태그 추가"],
  "info.date": ["Date", "날짜"],
  "info.place": ["Place", "장소"],
  "info.onMap": ["Show on map", "지도에서 보기"],
  "info.comments": ["Comments", "댓글"],
  "common.delete": ["Delete", "삭제"],
  "info.addComment": ["Add a comment…", "댓글 달기…"],
  "info.details": ["Details", "정보"],
  "info.dlOriginal": ["Download original", "원본 받기"],
  "info.dlJpeg": ["Download JPEG", "JPEG 받기"],
  "info.dlLive": ["Live video", "라이브 영상"],
  "info.setCover": ["Set as cover", "앨범 커버로"],
  "info.coverSet": ["Cover updated", "커버를 바꿨어요"],
  "place.search": ["Search places", "장소 검색"],
  "place.clear": ["Remove location", "위치 지우기"],
  "place.searching": ["Searching…", "찾는 중…"],
  "place.noResults": ["No results", "결과가 없어요"],
  "up.busy": ["Wait for the current upload to finish", "지금 업로드가 끝난 뒤에 올릴 수 있어요"],
  "up.reading": ["Reading photos…", "사진 확인 중…"],
  "up.withLocation": ["{n} with location", "위치 {n}"],
  "up.dups": ["{n} duplicate skipped", "중복 {n}개 제외"],
  "up.errors": ["{n} unsupported", "불가 {n}"],
  "up.large": ["Large", "대용량"],
  "up.title": ["Upload {n}", "{n}개 올리기"],
  "up.uploading": ["Uploading", "업로드 중"],
  "up.libraryOnly": ["Library only", "보관함에만"],
  "up.go": ["Upload", "업로드"],
  "up.st.dup": ["Already added", "이미 있음"],
  "up.st.processing": ["Processing", "처리 중"],
  "up.st.uploading": ["Uploading {i}/{n}", "올리는 중 {i}/{n}"],
  "up.st.queued": ["Queued", "대기"],
  "up.st.saving": ["Saving", "저장 중"],
  "up.st.done": ["Done", "완료"],
  "up.st.fail": ["Failed", "실패"],
  "save.failedNow": ["Couldn't save: {e}", "저장 실패: {e}"],
  "up.partial": ["{n} uploaded · {f} failed", "{n}개 올림 · {f}개 실패"],
  "up.allDone": ["Uploaded {n}", "{n}개 모두 올렸어요"],
  "set.removeConfirm": ["Remove {repo} from this device? The repository stays.", "이 기기에서 {repo}를 제거할까요? 저장소는 그대로예요."],
  "set.cacheCleared": ["Cache cleared", "캐시를 비웠어요"],
  "select.none": ["Select photos first", "사진을 먼저 선택하세요"],
  "app.title": ["Moa — shared albums", "Moa — 공유앨범"],
  "media.unsupported": ["Unsupported", "지원하지 않는 형식"],
  "media.tooBig": ["Over 100 MB", "100MB 초과"],
  "media.heic": ["This browser can't read HEIC — use Safari or convert to JPEG", "이 브라우저는 HEIC를 열 수 없어요 — Safari를 쓰거나 JPEG로 바꿔 주세요"],
  "media.decode": ["Can't open this image", "이미지를 열 수 없어요"],
  "gh.network": ["Can't reach GitHub", "GitHub에 연결할 수 없어요"],
  "gh.401": ["Token invalid or expired", "토큰이 올바르지 않거나 만료됐어요"],
  "gh.403": ["No write access to this repository", "이 저장소에 쓸 권한이 없어요"],
  "gh.404": ["Repository not found", "저장소를 찾을 수 없어요"],
  "gh.other": ["GitHub error {s}", "GitHub 오류 {s}"],
  "gh.conflict": ["Keeps conflicting with other changes. Try again shortly.", "다른 변경과 계속 충돌해요. 잠시 후 다시 시도하세요"],
  "gh.missing": ["Missing file: {p}", "파일이 없어요: {p}"],
  "aria.switchAlbum": ["Switch album", "앨범 바꾸기"],
  "aria.search": ["Search", "검색"],
  "search.ph": ["Search tags, places, captions, people", "태그, 장소, 설명, 사람 검색"],
  "view.date": ["Date", "날짜"],
  "view.place": ["Places", "장소"],
  "view.tag": ["Tags", "태그"],
  "aria.close": ["Close", "닫기"],
  "aria.playLive": ["Play Live Photo", "라이브 포토 재생"],
  "aria.prev": ["Previous", "이전"],
  "aria.next": ["Next", "다음"],
  "sync.purging": ["Erasing history…", "기록 지우는 중…"],
  "enc.encrypt": ["Encrypt", "암호화"],
  "enc.pass": ["Album passphrase", "앨범 암호"],
  "enc.pass2": ["Confirm passphrase", "암호 확인"],
  "enc.lost": ["A lost passphrase can't be recovered.", "암호를 잃어버리면 복구할 수 없어요."],
  "enc.short": ["Use at least 8 characters", "8자 이상으로 정해 주세요"],
  "enc.mismatch": ["Passphrases don't match", "암호가 서로 달라요"],
  "enc.on": ["Encrypted", "암호화됨"],
  "enc.change": ["Change passphrase", "암호 바꾸기"],
  "enc.current": ["Current passphrase", "지금 암호"],
  "enc.new": ["New passphrase", "새 암호"],
  "enc.changed": ["Passphrase changed", "암호를 바꿨어요"],
  "enc.lockHere": ["Lock on this device", "이 기기에서 잠그기"],
  "enc.locked": ["Encrypted album", "암호화된 앨범"],
  "lock.title": ["This album is encrypted", "암호화된 앨범이에요"],
  "lock.pass": ["Album passphrase", "앨범 암호"],
  "lock.remember": ["Remember on this device", "이 기기에서 기억하기"],
  "lock.unlock": ["Unlock", "열기"],
  "lock.unlocking": ["Unlocking…", "여는 중…"],
  "lock.wrong": ["Wrong passphrase", "암호가 맞지 않아요"],
  "purge.also": ["Also erase from history", "기록에서도 완전히 지우기"],
  "purge.title": ["Erase history", "기록 완전 삭제"],
  "purge.confirm": ["Erase history?", "기록을 완전히 지울까요?"],
  "purge.body": ["Deleted photos can no longer be recovered. The album stays as it is now.", "지운 사진을 더 이상 되살릴 수 없어요. 지금 앨범은 그대로 남아요."],
  "purge.go": ["Erase", "지우기"],
  "purge.done": ["History erased", "기록을 완전히 지웠어요"],
  "purge.failed": ["Couldn't erase history ({e})", "기록을 지우지 못했어요 ({e})"],
  "purge.unsaved": ["Changes are still unsaved", "아직 저장 안 된 변경이 있어요"],
  "rec.title": ["Recovery code", "복구 코드"],
  "rec.body": ["Opens this album if the passphrase is lost. Keep it somewhere safe — it's shown only now.", "암호를 잊었을 때 앨범을 여는 코드예요. 지금만 보여주니 안전한 곳에 보관하세요."],
  "rec.save": ["Save as file", "파일로 저장"],
  "rec.set": ["Set", "만들어 둠"],
  "rec.notSet": ["Not set", "없음"],
  "rec.none": ["Make a code that opens this album if the passphrase is lost.", "암호를 잊었을 때 앨범을 열 수 있는 코드를 만들어요."],
  "rec.replace": ["A new code replaces the old one.", "새 코드를 만들면 예전 코드는 쓸 수 없어요."],
  "rec.create": ["Create", "만들기"],
  "rec.new": ["New code", "새 코드"],
  "rec.missing": ["This album has no recovery code. A member whose device still opens it can set a new passphrase in Settings.", "이 앨범엔 복구 코드가 없어요. 이 앨범이 열려 있는 멤버의 기기에서 설정 → 암호 바꾸기로 새 암호를 정할 수 있어요."],
  "rec.wrong": ["That code doesn't open this album", "이 앨범의 복구 코드가 아니에요"],
  "rec.setNew": ["Set a new passphrase", "새 암호 정하기"],
  "lock.forgot": ["Forgot passphrase?", "암호를 잊으셨나요?"],
  "lock.usePass": ["Use passphrase", "암호로 열기"],
  "sync.converting": ["{s}", "{s}"],
  "conv.encryptTitle": ["Encrypt this album", "이 앨범 암호화하기"],
  "conv.encryptBody": ["Every photo is stored again, encrypted, then the unencrypted copies are erased from history. Members will need the passphrase.", "모든 사진을 암호화해서 다시 저장하고, 암호화 전 사본은 기록에서 지워요. 멤버들은 암호가 있어야 열 수 있어요."],
  "conv.encrypt": ["Encrypt", "암호화"],
  "conv.decryptTitle": ["Turn off encryption", "암호화 끄기"],
  "conv.decryptBody": ["Photos are stored unencrypted again. Members no longer need the passphrase.", "사진을 암호화하지 않은 상태로 다시 저장해요. 멤버들은 더 이상 암호가 필요 없어요."],
  "conv.decrypt": ["Turn off", "끄기"],
  "conv.encrypting": ["Encrypting", "암호화하는 중"],
  "conv.decrypting": ["Decrypting", "암호 푸는 중"],
  "conv.resumeEncrypt": ["Continue encrypting", "암호화 이어서 하기"],
  "conv.resumeDecrypt": ["Continue turning off encryption", "암호화 끄기 이어서 하기"],
  "conv.encrypted": ["Album encrypted", "앨범을 암호화했어요"],
  "conv.decrypted": ["Encryption turned off", "암호화를 껐어요"],
  "conv.failed": ["Stopped: {e} — you can continue from Settings", "멈췄어요: {e} — 설정에서 이어서 할 수 있어요"],
  "conv.paused": ["switched album", "다른 앨범으로 이동함"],
  "conv.restart": ["this device lost the new key; start again", "이 기기에서 새 키를 잃어버렸어요. 처음부터 다시 해주세요"],
  "common.copy": ["Copy", "복사"],
  "common.copied": ["Copied", "복사했어요"],
  "inv.byLink": ["Link or QR code", "링크 · QR 코드"],
  "inv.once": ["One-time QR", "1회용 QR"],
  "inv.week": ["Link for 7 days", "7일 링크"],
  "inv.withKey": ["Include the album key", "앨범 키 포함"],
  "inv.onceNote": ["Works once, until {d}", "한 번만 쓸 수 있어요 · {d}까지"],
  "inv.weekNote": ["Anyone with the link can ask to join until {d}", "{d}까지 링크를 가진 누구나 참여를 요청할 수 있어요"],
  "inv.until": ["until {d}", "{d}까지"],
  "inv.revoke": ["Revoke", "취소"],
  "inv.letIn": ["{u} joined through your invite", "{u}님이 초대 링크로 들어왔어요"],
  "inv.needScope": ["Invite links need one more GitHub permission.", "초대 링크를 쓰려면 GitHub 권한을 하나 더 받아야 해요."],
  "inv.relogin": ["Sign in again", "다시 로그인"],
  "join.enterCode": ["Enter invite code", "초대 코드 입력"],
  "join.code": ["Invite code or link", "초대 코드 또는 링크"],
  "join.next": ["Next", "다음"],
  "join.badCode": ["That isn't an invite code", "초대 코드가 아니에요"],
  "join.signin": ["You're invited to a Moa album. Sign in with GitHub to join.", "Moa 앨범에 초대받았어요. GitHub로 로그인하면 참여할 수 있어요."],
  "join.ask": ["Join {name} from {by}?", "{by}님의 {name} 앨범에 참여할까요?"],
  "join.join": ["Join", "참여하기"],
  "join.waiting": ["Asked to join {name}. You're in as soon as {by} opens Moa.", "{name} 참여를 요청했어요. {by}님이 Moa를 열면 바로 들어가요."],
  "join.gone": ["This invite was already used or has expired.", "이미 사용했거나 만료된 초대예요."],
  "join.own": ["This is your own invite.", "내가 만든 초대예요."],
  "home.fresh": ["New", "새 소식"],
  "up.stop": ["Stop", "중지"],
  "up.stopping": ["Stopping…", "멈추는 중…"],
  "up.resuming": ["Continuing the upload ({n} left)", "남은 {n}개를 이어서 올려요"],
  "opt.notify": ["Notify when uploads finish", "업로드·다운로드 완료 알림"],
  "chip.photos": ["Photos", "사진"],
  "dl.short": ["Download", "저장"],
  "dl.title": ["Download {n} {n|item|items}", "{n}개 받기"],
  "dl.all": ["Download all", "전체 받기"],
  "dl.zip": ["ZIP file", "ZIP 파일"],
  "dl.toPhotos": ["Save to Photos", "사진 앱에 저장"],
  "dl.preparing": ["Getting photos", "사진 받는 중"],
  "dl.ready": ["Your download is ready", "다운로드가 준비됐어요"],
  "dl.saveZip": ["Save ZIP", "ZIP 저장"],
  "dl.savePart": ["Save part {k}", "{k}번째 ZIP 저장"],
  "dl.saveN": ["Save {n} {n|file|files}", "{n}개 저장"],
  "ai.opt": ["Smart tags & search", "자동 태그 · 설명으로 검색"],
  "ai.offNote": ["Off · on-device AI", "꺼짐 · 기기 안에서 도는 AI"],
  "ai.starting": ["Starting…", "준비 중…"],
  "ai.downloading": ["Downloading the model {p}%", "모델 받는 중 {p}%"],
  "ai.analyzing": ["Looking at photos {n}/{total}", "사진 살펴보는 중 {n}/{total}"],
  "ai.ready": ["On", "켜짐"],
  "ai.failed": ["Couldn't start ({e})", "시작하지 못했어요 ({e})"],
  "ai.tags": ["Auto tags", "자동 태그"],
  "ai.consentTitle": ["Turn on smart tags?", "자동 태그를 켤까요?"],
  "ai.c1": ["Moa downloads an AI model (about 150 MB) from Hugging Face, once. Only the model is downloaded — your photos never leave this device.", "Hugging Face에서 AI 모델(약 150MB)을 한 번 내려받아요. 모델만 받을 뿐, 사진은 이 기기 밖으로 나가지 않아요."],
  "ai.c2": ["Photos are analyzed on this device to add tags like food or beach, and to find photos by description.", "사진을 이 기기에서 분석해 음식·바다 같은 태그를 달고, 설명으로 사진을 찾을 수 있게 해요."],
  "ai.c3": ["Auto tags are saved in the album, so its members can see them. Faces are not recognized.", "자동 태그는 앨범에 저장돼 멤버들도 볼 수 있어요. 얼굴은 인식하지 않아요."],
  "ai.c4": ["Turn it off anytime in Settings — the model and analysis data are then deleted from this device.", "설정에서 언제든 끌 수 있고, 끄면 이 기기의 모델과 분석 데이터가 지워져요."],
  "ai.agree": ["Agree and turn on", "동의하고 켜기"],
  "ai.offTitle": ["Turn off smart tags?", "자동 태그를 끌까요?"],
  "ai.offBody": ["The model and analysis data on this device are deleted.", "이 기기의 모델과 분석 데이터를 지워요."],
  "ai.clearTags": ["Also remove auto tags from this album", "이 앨범의 자동 태그도 지우기"],
  "ai.turnOff": ["Turn off", "끄기"],
  "ai.offDone": ["Smart tags turned off", "자동 태그를 껐어요"],
};
